<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" AutoSync="OnInsert" Type="System.DateTime" DbType="DateTime2 NULL" IsDbGenerated="true" CanBeNull="true" />
      <Association Name="User_Organizer" Member="Organizers" ThisKey="UserId" OtherKey="UserId" Type="Organizer" />
      <Association Name="User_Vendor" Member="Vendors" ThisKey="UserId" OtherKey="UserId" Type="Vendor" />
    </Type>
  </Table>
  <Table Name="dbo.Organizers" Member="Organizers">
    <Type Name="Organizer">
      <Column Name="OrganizerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrganizationName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ContactEmail" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" AutoSync="OnInsert" Type="System.DateTime" DbType="DateTime2  NULL" IsDbGenerated="true" CanBeNull="true" />
      <Association Name="Organizer_Event" Member="Events" ThisKey="OrganizerId" OtherKey="OrganizerId" Type="Event" />
      <Association Name="User_Organizer" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VendorAssignments" Member="VendorAssignments">
    <Type Name="VendorAssignment">
      <Column Name="AssignmentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SpaceNumber" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="AssignedAt" AutoSync="OnInsert" Type="System.DateTime" DbType="DateTime2 NULL" IsDbGenerated="true" CanBeNull="true" />
      <Association Name="VendorApplication_VendorAssignment" Member="VendorApplication" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="VendorApplication" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VendorApplications" Member="VendorApplications">
    <Type Name="VendorApplication">
      <Column Name="ApplicationId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VendorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="AppliedAt" AutoSync="OnInsert" Type="System.DateTime" DbType="DateTime2 NULL" IsDbGenerated="true" CanBeNull="true" />
      <Association Name="VendorApplication_VendorAssignment" Member="VendorAssignments" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="VendorAssignment" />
      <Association Name="Vendor_VendorApplication" Member="Vendor" ThisKey="VendorId" OtherKey="VendorId" Type="Vendor" IsForeignKey="true" />
      <Association Name="Event_VendorApplication" Member="Event" ThisKey="EventId" OtherKey="EventId" Type="Event" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Payments" Member="Payments">
    <Type Name="Payment">
      <Column Name="PaymentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VendorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="PlatformFee" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="OrganizerRevenue" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Vendor_Payment" Member="Vendor" ThisKey="VendorId" OtherKey="VendorId" Type="Vendor" IsForeignKey="true" />
      <Association Name="Event_Payment" Member="Event" ThisKey="EventId" OtherKey="EventId" Type="Event" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Vendors" Member="Vendors">
    <Type Name="Vendor">
      <Column Name="VendorId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BusinesName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ContactEmail" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" AutoSync="OnInsert" Type="System.DateTime" DbType="DateTime2 NULL" IsDbGenerated="true" CanBeNull="true" />
      <Association Name="Vendor_VendorApplication" Member="VendorApplications" ThisKey="VendorId" OtherKey="VendorId" Type="VendorApplication" />
      <Association Name="Vendor_Payment" Member="Payments" ThisKey="VendorId" OtherKey="VendorId" Type="Payment" />
      <Association Name="User_Vendor" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Events" Member="Events">
    <Type Name="Event">
      <Column Name="EventId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrganizerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="EventDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="MaxVendors" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" AutoSync="OnInsert" Type="System.DateTime" DbType="DateTime2 NULL" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="VarChar(50)" CanBeNull="false" />
      <Association Name="Event_VendorApplication" Member="VendorApplications" ThisKey="EventId" OtherKey="EventId" Type="VendorApplication" />
      <Association Name="Event_Payment" Member="Payments" ThisKey="EventId" OtherKey="EventId" Type="Payment" />
      <Association Name="Organizer_Event" Member="Organizer" ThisKey="OrganizerId" OtherKey="OrganizerId" Type="Organizer" IsForeignKey="true" />
    </Type>
  </Table>
</Database>